### PR TITLE
Reviewer SL: Added chronos log cleanup script

### PR DESCRIPTION
**Pull request by Tom-Rees**

### CODE REVIEW

**Comment by steelyvoid** [comment]
Looks good.   Wasn't there a debian install script change we needed as well?

**Comment by Tom-Rees** [comment]
I thought that the current install script install script already copied files from etc/ into /etc/? Although this does need testing and so I was going to add a test reminder to the 'making a release' article to avoid having to set up a test box ourselves?

**Comment by steelyvoid** [comment]
Sorry - I'd forgotten that.  Might be worth mentioning that as a comment on the merge when you submit the PC version of this change (otherwise Andy will probably ask the same question)

**Comment by steelyvoid** [comment]
Looks good then

**Comment by Tom-Rees** [comment]
In the corresponding PC commit (https://github.com/Metaswitch/chronos/commit/f9855e6d93b51a148ba9fda22dd6cdb3fbf2b853), debian/control was also updated, so copying that change here and in track_2.

**Comment by steelyvoid** [comment]
Thought it was too easy:).  Looks good

**Pull request merged**
